### ISSUE TITLE
Decorate the axios response with the duration of the response.

### ISSUE THREAD

**Issue by SalvadorCali** [mia-platform/custom-plugin-lib#275]
## The feature or bug you are proposing
Decorate the axios response with the duration of the response.

## The description of the bug or the rationale of your proposal
Due to the need to proxy various calls from a system to another it could be useful to decorate the axios response to include the duration of the response.

## A snippet of code for replicating the issue or showing the proposal usage if applicable
[Here](https://git.tools.mia-platform.eu/clients/helvetia/services/request-manager/-/blob/master/src/services/AfterSalesOperationsService/index.js#L131) you can find an example of this implementation for the `request-manager`.

## The expected result for your bug
It could be useful to use this value to log if the response doesn't respect a certain time limit or expose a metric to track the time of this kind of response.

### Your environment

node: `v16.16.0`

custom-plugin-lib: `v5.1.1`

os: `Ubuntu 20.04.4 LTS`

**Comment by fredmaggiowski** [comment]
Hi, the link to the repo you provided is private, could you share the example code directly in the feature request?

**Comment by SalvadorCali** [comment]
> Hi, the link to the repo you provided is private, could you share the example code directly in the feature request?
>
```
_addDurationToAxiosResponse() {
    axios.interceptors.response.use(
      (response) => {
        response.config.metadata.endTime = new Date()
        response.duration = response.config.metadata.endTime - response.config.metadata.startTime
        return response
      },
      (error) => {
        error.config.metadata.endTime = new Date()
        error.duration = error.config.metadata.endTime - error.config.metadata.startTime
        return Promise.reject(error)
      }
    )

    axios.interceptors.request.use(
      (config) => {
        config.metadata = { startTime: new Date() }
        return config
      }, (error) => {
        return Promise.reject(error)
      })
  }
```
> 
> Anyhow, this seems like an interesting feature, do you have time to submit a PR?
>
Yes, sure. We'll take it over in the next sprint.

**Comment by fredmaggiowski** [comment]
>Yes, sure. We'll take it over in the next sprint.

great! 🥳

**Comment by SimoneBergonzi** [comment]
We opened a [pr](https://github.com/mia-platform/custom-plugin-lib/pull/278) to track and return the request duration in the httpClient response object.

We were thinking how we could make these data available as a prometheus metric. 
The idea we came up with is to decorate the fastify instance with a function (let say `getHttpClientMetrics(prom-client)`) which returns a metric that can be used by the http client to track the requests duration and update `lc39` so that it retrieves the http client metrics from the decorated fastify instance and (if metrics are enabled) it registers the http client metrics along with the custom metrics.

What do you think?

**Comment by fredmaggiowski** [comment]
>We were thinking how we could make these data available as a prometheus metric.
The idea we came up with is to decorate the fastify instance with a function (let say getHttpClientMetrics(prom-client)) which returns a metric that can be used by the http client to track the requests duration and update lc39 so that it retrieves the http client metrics from the decorated fastify instance and (if metrics are enabled) it registers the http client metrics along with the custom metrics.

The prom client should already be in available in the fastify instance so I guess the HTTP client could already use it to register the duration metrics; however I'd make the feature only available with an opt-in feature flag since time duration series may have impacts on the amount of data stored in prometheus
